#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

if (file_exists($__bootstrap = __DIR__.'/bootstrap/autoload.php')) {
    require $__bootstrap;
}

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
));
